### ISSUE TITLE
Follow the exclude settings in `_config.yml`

### ISSUE THREAD

**Issue by pilgrimlyieu** [next-theme/hexo-generator-searchdb#39]
Here's Include/Exclude file(s) setting in `_config.yml`. Can the searchdb generator follows this setting?

```yml
# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
  - "private_content/*"
ignore:
```
